strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
train_module: Human Localization Module
localization_input: feature_transferred_lidar
#original 100
epochs: &epochs 30
# --------------------------------------
# Dataset parameters
# --------------------------------------
train_dataset:
  name: BaseDataset
  params:
    data_path: &data_path /home/ryan/MM-Fi/LEMT/data_raw_dual/mmfi_raw_dual_default.pkl
    split: [train_rdn_p3, val_rdn_p3] #rdn, xsub, xenv
val_dataset:
  name: BaseDataset
  params:
    data_path: *data_path
    split: test_rdn_p3
test_dataset:
  name: BaseDataset
  params:
    data_path: *data_path
    split: test_rdn_p3
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.0001
  weight_decay: 0.00001
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: CosineAnnealingWarmRestarts
sched_params:
  T_0: 6
  eta_min: 1.0e-06
# --------------------------------------
# Model parameters
# --------------------------------------
mode: train
model_name: HumanLocalizeP4Transformer
model_params:
  radius: 0.7
  nsamples: 32
  spatial_stride: 8
  temporal_kernel_size: 3
  temporal_stride: 1
  emb_relu: false
  dim: 1024
  depth: 5
  heads: 8
  dim_head: 128
  mlp_dim: 2048
  output_dim: 3
  features: 3
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: MSELoss
loss_params: null
# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params: 
      pad_type: 'start'
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'median'
      # data_type: 'mmwave'
  - name: Normalize
    params:
      feat_scale: null
  # - name: MultiFrameAggregate
  #   params:
  #     num_frames: 3
  # - name: ToITOP
  #   params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 3 # original 1.5
      # data_type: 'mmwave'
  # - name: AddNoisyPoints
  #   params:
  #     add_std: 0.2
  #     num_added: 8
  #     zero_centered: false
  # - name: RandomScale
  #   params:
  #     scale_min: 0.9
  #     scale_max: 1.1
  #   prob: 0.5
  # - name: RandomRotate
  #   params:
  #     deg: true
  #     angle_min: -10
  #     angle_max: 10
  #   prob: 0.5
  # - name: RandomTranslate
  #   params:
  #     translate_range: 0.01
  #   prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  # - name: FeatureTransfer
  #   params:
  #     feature_idx: [3,4]
  #     knn_k: 3
  #     transfer_type: 'empty' #'mmwave', 'empty'
  - name: FeatureTransfer
    params:
      feature_idx: [3,4]
      knn_k: 3
      transfer_type: 'mmwave'
  - name: Pad
    params:
      max_len: 256
      mm_len: 128
  # - name: RandomJitter
  #   params:
  #     jitter_std: 0.05
  #   prob: 0.5
  - name: ToTensor
    params: null
val_pipeline: &val_pipeline
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'median'
      # data_type: 'mmwave'
  # - name: ToITOP
  #   params: null
  # - name: MultiFrameAggregate
  #   params:
  #     num_frames: 3
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 3 # original 1.5
      # data_type: 'mmwave'
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  # - name: FeatureTransfer
  #   params:
  #     feature_idx: [3,4]
  #     knn_k: 3
  #     transfer_type: 'empty'
  - name: FeatureTransfer
    params:
      feature_idx: [3,4]
      knn_k: 3
      transfer_type: 'mmwave'
  - name: Pad
    params:
      max_len: 256
      mm_len: 128
      #lidar -> 512, mmwave -> 128
  - name: ToTensor
    params: null
test_pipeline:
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 5
  - name: GetCentroid
    params: 
      centroid_type: 'median'
      # data_type: 'mmwave'
  # - name: ToITOP
  #   params: null
  # - name: MultiFrameAggregate
  #   params:
  #     num_frames: 3
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 3 # original 1.5
      # data_type: 'mmwave'
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  # - name: FeatureTransfer
  #   params:
  #     feature_idx: [3,4]
  #     knn_k: 3
  #     transfer_type: 'empty'
  - name: FeatureTransfer
    params:
      feature_idx: [3,4]
      knn_k: 3
      transfer_type: 'mmwave'
  - name: Pad
    params:
      max_len: 256
      mm_len: 128
  - name: ToTensor
    params: null